### ISSUE TITLE
/service-worker.js 404 request failed, when deployed to production

### ISSUE THREAD

**Issue by MarkLyck** [hanford/next-offline#86]
I have read the documentation and the 3 other issues on here with a 404 issue and anything else I could find.

When I run `$ next build && NODE_ENV=production node server.js` everything gets served correctly on `localhost:3000`. No problems there.

However, as soon as I try to deploy my application to a production environment using now zeit I get an error:

A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE
main-8ae275bee0ba164baa7e.js:1 SW registration failed:
TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

^ One interesting note is that the error says "HTTP" response. but this is running on https. (might be related to the issue) but the request is https, so I think that's just a generic error message.

![image](https://user-images.githubusercontent.com/6841110/48979725-54631700-f0bf-11e8-9017-52f7b0accddd.png)

Full request URL: https://formula-stocks-oyjdhconcy.now.sh/service-worker.js

I followed the guide in the docs, and tried different variations I've seen from other issues.

I also tried to use createReadStream to server it directly in the response, but same problem.

Currently I'm trying the following solution from the README:

server.js
```
const { createServer } = require('https')
const { parse } = require('url')
const { join } = require('path')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  createServer((req, res) => {
    // Be sure to pass `true` as the second argument to `url.parse`.
    // This tells it to parse the query portion of the URL.
    const parsedUrl = parse(req.url, true)
    const { pathname, query } = parsedUrl

    if (pathname === '/service-worker.js') {
      const filePath = join(__dirname, '.next', pathname)
      app.serveStatic(req, res, filePath)
    } else if (pathname.indexOf('dashboard/articles/') > -1) {
      app.render(req, res, '/dashboard/articles/article', query)
    } else if (pathname.indexOf('articles/') > -1) {
      app.render(req, res, '/articles/article', query)
    } else {
      handle(req, res, parsedUrl)
    }
  }).listen(3000, err => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
```

next.config.js
```
const withPlugins = require('next-compose-plugins')
const withBundleAnalyzer = require('@zeit/next-bundle-analyzer')
const withOffline = require('next-offline')

module.exports = withPlugins([
  [
    withBundleAnalyzer,
    {
      analyzeServer: ['server', 'both'].includes(process.env.BUNDLE_ANALYZE),
      analyzeBrowser: ['browser', 'both'].includes(process.env.BUNDLE_ANALYZE),
      bundleAnalyzerConfig: {
        server: {
          analyzerMode: 'static',
          reportFilename: '../../bundles/server.html',
        },
        browser: {
          analyzerMode: 'static',
          reportFilename: '../bundles/client.html',
        },
      },
    },
  ],
  [withOffline],
])
```

the whole `.next` is ignored in both .gitignore and .nowignore

The `.next/server-worker.js` file is generated correctly on `next build`

I have no other files related to the service worker or next-offline.
next-offline is in my dependencies, and successfully installed in node_modules

next version: 7.0.2
next-offline: 3.2.1

Any ideas why this is happening when deployed in a prod environment?

Deployed application with the error: https://formula-stocks-snjnaoeivp.now.sh/ (this instance might no longer exist when you are reading this)

**Comment by hanford** [comment]
@MarkLyck can you try removing `next-compose-plugins`?

next-offline has a lot of problems with it, and we're trying to figure out whats going on over here: https://github.com/hanford/next-offline/issues/69

Your next config should look something like this:

```js
const withBundleAnalyzer = require('@zeit/next-bundle-analyzer')
const withOffline = require('next-offline')

const hasBundleAnalyzer = withBundleAnalyzer({
  analyzeServer: ['server', 'both'].includes(process.env.BUNDLE_ANALYZE),
  analyzeBrowser: ['browser', 'both'].includes(process.env.BUNDLE_ANALYZE),
  bundleAnalyzerConfig: {
    server: {
      analyzerMode: 'static',
      reportFilename: '../../bundles/server.html',
    },
    browser: {
      analyzerMode: 'static',
      reportFilename: '../bundles/client.html',
    },
  },
})

module.exports = withOffline(hasBundleAnalyzer)
```

Please report back if this does or doesn't help!

**Comment by hanford** [comment]
@MarkLyck can you share your package.json?

**Comment by MarkLyck** [comment]
@hanford

https://zeit.co/markl/formula-stocks/lruhnylguj/source?f=package.json

**Comment by hanford** [comment]
hmmm, bootstrapping a new next project with a custom server and next-offline is working on my end

https://github.com/hanford/next-offline-issue-86

Can you use `create-next-app` and try to replicate your website as much as possible to reproduce the issue?

The only thing in your `package.json` is we would want to be certain `    "now-start": "next start",` is never used.

Otherwise next won't invoke your server resulting it not handling the service-worker request.

You could verify that by creating a new dummy route in your custom server like `/foo` and verify that it responds with a 200

**Comment by MarkLyck** [comment]
@hanford ahh you are right. `now-start` was being run in production mode. It's solved now.

(it works fine for me with the compose-plugins by the way)

Thanks for the help!

**Comment by andreisocaciu** [comment]
I have the same problem. 
```
const withCss = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withOffline = require('next-offline');

const nextConfig = {
    target: 'serverless',
    cssModules: true,
};

const hasSass = withSass(nextConfig);
const hasCss = withCss(hasSass);
const hasOffline = withOffline(hasCss);

module.exports = hasOffline;
```
With this next.config.js I still get 404 on /service-worker.js.

**Comment by hanford** [comment]
@andreisocaciu can you open a new issue with as much information & and repo where this issue is reproducible?

**Comment by andreisocaciu** [comment]
I managed to make this work:

next.config.js:
```
const withCss = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withOffline = require('next-offline');

const nextConfig = {
    target: 'serverless',
    cssModules: true,
    workboxOpts: {
        swDest: 'static/service-worker.js', // this is the important part
    }
};

const hasSass = withSass(nextConfig);
const hasCss = withCss(hasSass);
const hasOffline = withOffline(hasCss);

module.exports = hasOffline;
```

now.json: (v2)
```
...
"routes": [
  {
    "src": "^/service-worker.js$",
    "dest": "/_next/static/service-worker.js",
    "headers": {
      "cache-control": "public, max-age=43200, immutable",
      "Service-Worker-Allowed": "/"
    }
  }
]
```

Great job with the package!
